# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87b3e2f44af41a3ca63b345bb99b6243c9e3e895e5f8118e44418a30be49036235c5b2d6719dc4aa03e2812f45a6fb3a88fdf7ec6bb62fd02ead91ea8d3d1879

test:
  secret_key_base: 2b281c9d7de9fac53dbed4b17e41def6bac88340729d308011caa2fcb0c6de131dbab16b4cd4729611f6325c0b62d5dd5463f72c2a00260ebe1799f2e7799e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
